### ISSUE TITLE
0 "translator" service definition is not a Closure. 

### ISSUE THREAD

**Issue by oookubox** [rvalitov/widgetkit-folder-ex#2]
Hi!

I coped folder "folder_ex", but i had this error:
0 "translator" service definition is not a Closure.

**Comment by rvalitov** [comment]
Thank you! This problem happens sometimes. I will push and updated release of this plugin today.

**Comment by rvalitov** [comment]
I made a patch. You can download it from [this link](https://github.com/rvalitov/widgetkit-folder-ex/archive/09fe7751df5265325ac1c53badd32402e688f0e7.zip). Just reinstall this plugin with the new version from the archive (upgrade instructions are in the [Wiki](https://github.com/rvalitov/widgetkit-folder-ex/wiki)). And after that please report if the problem is solved or not. If it will be OK, then I will add this patch into the next "official" release of this plugin. Thank you! Waiting for response from you...

**Comment by oookubox** [comment]
It worked , thanks .
However, images are displayed only if the files are named in Latin letters.
Files which consist of Russian letters are displayed as links.

**Comment by rvalitov** [comment]
I'm glad it's fine now. Can you please create another issue for this problem regarding the Russian letters? And provide some more details or a screenshot. I would like to reproduce this problem in order to solve it. Thank you!
